#!/bin/sh

# Script to automate the midi connection to sushi

#You can edit this file and enable the midi-connections for automatic midi connection at bootup
# To enable this service type
# 	sudo systemctl enable midi-connections

aconnect "pedalboard-midi" "Sushi"
while [ $? -ne 0 ]; do
    sleep 0.5
    aconnect "pedalboard-midi" "Sushi"
done

aconnect "Sushi" "pedalboard-midi"
while [ $? -ne 0 ]; do
    sleep 0.5
    aconnect "Sushi" "pedalboard-midi"
done
